lb_everywhere.settings:
  type: config_object
  label: 'Layout Builder Everywhere settings'
  mapping:
    region_map:
      type: sequence
      sequence:
        type: sequence
        sequence:
          type: string
